"""Generate an isolated, full-width RQ2 table test from the tracked project CSV.

The table has two large task columns. Each contains a metric-by-approach matrix.
The PNG/PDF are a conservative five-inch visual mock-up; the companion document
uses the paper's acmsmall class and options for an exact build when TeX is present.
"""

from __future__ import annotations

import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = ROOT / "evaluation/reports/tex_src/bigtable_rq12_perproject.csv"
STEM = HERE / "rq2-wide-layout-test"
PROJECTS = ["mediastore", "teastore", "teammates", "bigbluebutton", "jabref", "Average"]
SYSTEMS = [
    ("approach (GPT-5.6-terra)", "ArchLinker", "ArchLinker"),
    ("Artemis (GPT-5.6-terra)", "Artemis", "Artemis"),
    ("TransArC", "SWATTR", "TransArc"),
]
DISPLAY = {
    "mediastore": "MediaStore",
    "teastore": "TeaStore",
    "teammates": "Teammates",
    "bigbluebutton": "BigBlueButton",
    "jabref": "JabRef",
    "Average": "Average",
}


def read_rows() -> dict[tuple[str, str], dict[str, str]]:
    with SOURCE.open(newline="", encoding="utf-8") as stream:
        rows = {(row["system"], row["project"]): row for row in csv.DictReader(stream)}
    expected = {(system, project) for system, _, _ in SYSTEMS for project in PROJECTS}
    assert expected <= rows.keys(), sorted(expected - rows.keys())
    return rows


def f2(value: str) -> str:
    return f"{float(value):.2f}".removeprefix("0")


def pair(row: dict[str, str], f1: str, f2_name: str) -> str:
    return f"{f2(row[f1])}/{f2(row[f2_name])}"


def task_values(rows: dict[tuple[str, str], dict[str, str]], project: str, task: str) -> list[list[str]]:
    selected = [rows[(system, project)] for system, _, _ in SYSTEMS]
    if task == "dm":
        return [
            [
                "Link \\fone/\\ftwo (CMR\\%)",
                *[
                    pair(row, "doc_to_model_link_f1", "doc_to_model_link_f2")
                    + f" ({float(row['doc_to_model_component_miss_rate']):.1f})"
                    for row in selected
                ],
            ],
        ]
    return [
        ["Link \\fone/\\ftwo", *[pair(row, "doc_to_code_file_f1", "doc_to_code_file_f2") for row in selected]],
        ["Worst \\fone/\\ftwo", *[pair(row, "doc_to_code_worst_component_f1", "doc_to_code_worst_component_f2") for row in selected]],
        ["Harm. \\fone/\\ftwo", *[pair(row, "doc_to_code_harmonic_component_f1", "doc_to_code_harmonic_component_f2") for row in selected]],
    ]


def inner_header(task: str) -> str:
    if task == "dm":
        return (
            "\\begin{tabular*}{\\linewidth}{@{}@{\\extracolsep{\\fill}}ccc@{}}"
            "\\multicolumn{3}{c}{Link \\fone/\\ftwo (CMR\\%)}\\\\"
            "\\approach{} & \\Artemis{} & SWATTR\\end{tabular*}"
        )
    return (
        "\\begin{tabular*}{\\linewidth}{@{}l@{\\extracolsep{\\fill}}ccc@{}}"
        "\\multicolumn{4}{c}{\\fone/\\ftwo}\\\\"
        "Metric & \\approach{} & \\Artemis{} & \\TransArc{}\\end{tabular*}"
    )


def inner_body(values: list[list[str]], task: str) -> str:
    if task == "dm":
        return (
            "\\begin{tabular*}{\\linewidth}[t]{@{}@{\\extracolsep{\\fill}}ccc@{}}"
            + " & ".join(values[0][1:])
            + "\\end{tabular*}"
        )
    rows = [" & ".join(row) for row in values]
    return "\\begin{tabular*}{\\linewidth}[t]{@{}l@{\\extracolsep{\\fill}}ccc@{}}" + "\\\\".join(rows) + "\\end{tabular*}"


def write_tex(rows: dict[tuple[str, str], dict[str, str]]) -> None:
    lines = [
        "% TEST LAYOUT, generated by verification/rq2-wide-layout-test.py.",
        "% Source: evaluation/reports/tex_src/bigtable_rq12_perproject.csv.",
        "% Input this fragment from paper/main.tex to test it in the paper class.",
        "\\begin{table}[t]",
        "\\caption{RQ2 per-project results on GPT-5.6-terra. The doc-model task reports link \\fone/\\ftwo and component miss rate (CMR); the doc-code task reports link, worst-component, and harmonic-component \\fone/\\ftwo. \\approach{} and \\Artemis{} are means of three runs. SWATTR and \\TransArc{} are the respective stages of one deterministic pipeline.}",
        "\\label{tab:rq2-wide-test}",
        "\\centering\\footnotesize",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\renewcommand{\\arraystretch}{0.98}",
        "\\begin{tabular*}{\\linewidth}{@{}l@{\\extracolsep{\\fill}}p{.38\\linewidth}p{.43\\linewidth}@{}}",
        "\\toprule",
        "Project & \\centering doc-model & \\centering\\arraybackslash doc-code \\\\",
        "\\cmidrule(lr){2-2}\\cmidrule(l){3-3}",
        " & " + inner_header("dm") + " & " + inner_header("dc") + " \\\\",
        "\\midrule",
    ]
    for project in PROJECTS:
        if project == "Average":
            lines.append("\\midrule")
        lines.append(
            DISPLAY[project]
            + " & "
            + inner_body(task_values(rows, project, "dm"), "dm")
            + " & "
            + inner_body(task_values(rows, project, "dc"), "dc")
            + " \\\\")
        if project != "Average":
            lines.append("\\addlinespace[0.5pt]")
    lines += ["\\bottomrule", "\\end{tabular*}", "\\end{table}"]
    STEM.with_suffix(".tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_preview(rows: dict[tuple[str, str], dict[str, str]]) -> tuple[int, int]:
    plt.rcParams.update({"font.family": "DejaVu Serif", "font.size": 6.4})
    fig = plt.figure(figsize=(5.0, 3.2), dpi=300)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set(xlim=(0, 1), ylim=(0, 1))
    ax.axis("off")
    artists = []

    def label(x: float, y: float, value: str, *, ha: str = "center", size: float = 7, weight: str = "normal") -> None:
        artists.append(ax.text(x, y, value, ha=ha, va="center", fontsize=size, weight=weight))

    left, project_right, gap, right = 0.02, 0.17, 0.018, 0.98
    available = right - project_right - gap
    task_widths = [available * 0.38 / 0.81, available * 0.43 / 0.81]
    task_lefts = [project_right, project_right + task_widths[0] + gap]
    centers_by_task = []
    for task_index, task_left in enumerate(task_lefts):
        task_width = task_widths[task_index]
        if task_index == 0:
            centers_by_task.append([task_left + (i + 0.5) * task_width / 3 for i in range(3)])
        else:
            metric_width = 0.30 * task_width
            approach_width = (task_width - metric_width) / 3
            centers_by_task.append([
                task_left + metric_width / 2,
                *[task_left + metric_width + (i + 0.5) * approach_width for i in range(3)],
            ])
    label(left, 0.973, "RQ2 wide layout test · GPT-5.6-terra · F scores rounded to two decimals", ha="left", size=7.4, weight="bold")
    ax.plot([left, right], [0.925, 0.925], color="black", lw=0.6)
    label(left, 0.88, "Project", ha="left", weight="bold")
    label(task_lefts[0] + task_widths[0] / 2, 0.88, "doc-model", size=7.4, weight="bold")
    label(task_lefts[1] + task_widths[1] / 2, 0.88, "doc-code", size=7.4, weight="bold")
    ax.plot([task_lefts[0], task_lefts[0] + task_widths[0]], [0.85, 0.85], color="black", lw=0.35)
    ax.plot([task_lefts[1], right], [0.85, 0.85], color="black", lw=0.35)
    dm_centers, dc_centers = centers_by_task
    label(task_lefts[0] + task_widths[0] / 2, 0.815, "Link F₁/F₂ (CMR%)", size=5.6)
    label(task_lefts[1] + task_widths[1] / 2, 0.815, "F₁/F₂", size=5.6)
    for center, heading in zip(dm_centers, ("ArchLinker", "Artemis", "SWATTR")):
        label(center, 0.775, heading, size=5.8)
    for center, heading in zip(dc_centers, ("Metric", "ArchLinker", "Artemis", "TransArc")):
        label(center, 0.775, heading, size=5.8)
    ax.plot([left, right], [0.745, 0.745], color="black", lw=0.4)

    for row_index, project in enumerate(PROJECTS):
        y = 0.68 - row_index * 0.108
        label(left, y, DISPLAY[project], ha="left", weight="bold" if project == "Average" else "normal")
        dm_values = task_values(rows, project, "dm")
        dc_values = task_values(rows, project, "dc")
        for task_index, (values, offsets) in enumerate(((dm_values, (0.0,)), (dc_values, (0.032, 0.0, -0.032)))):
            centers = centers_by_task[task_index]
            for offset, row in zip(offsets, values):
                if task_index == 0:
                    for value_index, value in enumerate(row[1:]):
                        label(centers[value_index], y + offset, value, size=5.9)
                else:
                    metric = row[0].replace("\\fone/\\ftwo", "F₁/F₂").replace("\\%", "%")
                    label(centers[0], y + offset, metric, ha="center", size=5.3)
                    for value_index, value in enumerate(row[1:]):
                        label(centers[value_index + 1], y + offset, value, size=6.1)
    ax.plot([left, right], [0.194, 0.194], color="black", lw=0.4)
    ax.plot([left, right], [0.085, 0.085], color="black", lw=0.6)
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    pixel_width = fig.get_figwidth() * fig.dpi
    for artist in artists:
        box = artist.get_window_extent(renderer)
        assert box.x0 >= 0 and box.x1 <= pixel_width, f"Text outside five-inch preview: {artist.get_text()}"
    fig.savefig(STEM.with_suffix(".png"), dpi=300)
    fig.savefig(STEM.with_suffix(".pdf"))
    dimensions = tuple(int(v) for v in fig.canvas.get_width_height())
    plt.close(fig)
    return dimensions


if __name__ == "__main__":
    data = read_rows()
    write_tex(data)
    pixels = write_preview(data)
    print(f"PASS: 6 project rows x 2 task matrices x 3 approaches; all F scores have two decimals; five-inch preview {pixels[0]}x{pixels[1]} px; no text extends past page width")
    print(f"Wrote {STEM.with_suffix('.tex').relative_to(ROOT)}")
    print(f"Wrote {STEM.with_suffix('.png').relative_to(ROOT)}")
    print(f"Wrote {STEM.with_suffix('.pdf').relative_to(ROOT)}")
