"""Generate an isolated, full-width RQ2 table test from the tracked project CSV.

The PNG/PDF are a five-inch visual mock-up, not a LaTeX compilation.
"""

from __future__ import annotations

import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = ROOT / "evaluation/reports/tex_src/bigtable_rq12_perproject.csv"
STEM = HERE / "rq2-wide-layout-test"
PROJECTS = ["mediastore", "teastore", "teammates", "bigbluebutton", "jabref", "Average"]
SYSTEMS = [
    ("approach (GPT-5.6-terra)", "ArchLinker", "ArchLinker"),
    ("Artemis (GPT-5.6-terra)", "Artemis", "Artemis"),
    ("TransArC", "SWATTR", "TransArc"),
]
DISPLAY = {
    "mediastore": "MediaStore",
    "teastore": "TeaStore",
    "teammates": "Teammates",
    "bigbluebutton": "BigBlueButton",
    "jabref": "JabRef",
    "Average": "Average",
}


def read_rows() -> dict[tuple[str, str], dict[str, str]]:
    with SOURCE.open(newline="", encoding="utf-8") as stream:
        rows = {(row["system"], row["project"]): row for row in csv.DictReader(stream)}
    expected = {(system, project) for system, _, _ in SYSTEMS for project in PROJECTS}
    assert expected <= rows.keys(), sorted(expected - rows.keys())
    return rows


def f3(value: str) -> str:
    return f"{float(value):.3f}".removeprefix("0")


def f2(value: str) -> str:
    return f"{float(value):.2f}".removeprefix("0")


def dm_lines(row: dict[str, str]) -> list[str]:
    return [
        f"{f3(row['doc_to_model_link_f1'])}/{f3(row['doc_to_model_link_f2'])}",
        f"CMR {float(row['doc_to_model_component_miss_rate']):.1f}",
    ]


def dc_lines(row: dict[str, str]) -> list[str]:
    return [
        f"{f3(row['doc_to_code_file_f1'])}/{f3(row['doc_to_code_file_f2'])}",
        f"{f2(row['doc_to_code_worst_component_f1'])}/{f2(row['doc_to_code_worst_component_f2'])}",
        f"{f2(row['doc_to_code_harmonic_component_f1'])}/{f2(row['doc_to_code_harmonic_component_f2'])}",
    ]


def write_tex(rows: dict[tuple[str, str], dict[str, str]]) -> None:
    lines = [
        "% TEST LAYOUT, generated by verification/rq2-wide-layout-test.py.",
        "% Source: evaluation/reports/tex_src/bigtable_rq12_perproject.csv.",
        "% Input this fragment from paper/main.tex to test it in the paper class.",
        "\\begin{table}[t]",
        "\\caption{RQ2 full-width layout test on GPT-5.6-terra. Each doc-model cell shows link \\fone/\\ftwo and CMR\\%; each doc-code cell shows link, worst-component, and harmonic-component \\fone/\\ftwo from top to bottom. The two deterministic headings are stages of one SWATTR$\\rightarrow$\\TransArc{} pipeline.}",
        "\\label{tab:rq2-wide-test}",
        "\\centering\\scriptsize",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\begin{tabular*}{\\linewidth}{@{}l@{\\extracolsep{\\fill}}cccccc@{}}",
        "\\toprule",
        " & \\multicolumn{3}{c}{doc-model} & \\multicolumn{3}{c}{doc-code} \\\\",
        "\\cmidrule(lr){2-4}\\cmidrule(l){5-7}",
        "Project & \\approach{} & \\Artemis{} & SWATTR & \\approach{} & \\Artemis{} & \\TransArc{} \\\\",
        "\\midrule",
    ]
    for project in PROJECTS:
        cells = []
        for system, _, _ in SYSTEMS:
            cells.append("\\shortstack[c]{" + "\\\\".join(dm_lines(rows[(system, project)])) + "}")
        for system, _, _ in SYSTEMS:
            cells.append("\\shortstack[c]{" + "\\\\".join(dc_lines(rows[(system, project)])) + "}")
        if project == "Average":
            lines.append("\\midrule")
        lines.append(DISPLAY[project] + " & " + " & ".join(cells) + " \\\\")
        if project != "Average":
            lines.append("\\addlinespace[1pt]")
    lines += ["\\bottomrule", "\\end{tabular*}", "\\end{table}"]
    STEM.with_suffix(".tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_preview(rows: dict[tuple[str, str], dict[str, str]]) -> tuple[int, int]:
    plt.rcParams.update({"font.family": "DejaVu Serif", "font.size": 7})
    fig = plt.figure(figsize=(5.0, 3.45), dpi=300)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set(xlim=(0, 1), ylim=(0, 1))
    ax.axis("off")
    artists = []

    def label(x: float, y: float, value: str, *, ha: str = "center", size: float = 7, weight: str = "normal") -> None:
        artists.append(ax.text(x, y, value, ha=ha, va="center", fontsize=size, weight=weight))

    left, split, right = 0.02, 0.18, 0.98
    width = (right - split) / 6
    centers = [split + (i + 0.5) * width for i in range(6)]
    label(left, 0.977, "RQ2 wide layout test · GPT-5.6-terra", ha="left", size=8, weight="bold")
    label(left, 0.935, "Doc-model: link F₁/F₂, CMR%.  Doc-code: link, worst, harmonic F₁/F₂ (top to bottom).", ha="left", size=5.6)
    ax.plot([left, right], [0.898, 0.898], color="black", lw=0.6)
    label((centers[0] + centers[2]) / 2, 0.86, "doc-model", size=8)
    label((centers[3] + centers[5]) / 2, 0.86, "doc-code", size=8)
    ax.plot([split, split + 3 * width - 0.01], [0.832, 0.832], color="black", lw=0.35)
    ax.plot([split + 3 * width + 0.01, right], [0.832, 0.832], color="black", lw=0.35)
    label(left, 0.788, "Project", ha="left", weight="bold")
    for i, (_, dm_head, dc_head) in enumerate(SYSTEMS):
        label(centers[i], 0.788, dm_head)
        label(centers[i + 3], 0.788, dc_head)
    ax.plot([left, right], [0.746, 0.746], color="black", lw=0.4)

    for row_index, project in enumerate(PROJECTS):
        y = 0.668 - row_index * 0.108
        label(left, y, DISPLAY[project], ha="left", weight="bold" if project == "Average" else "normal")
        for system_index, (system, _, _) in enumerate(SYSTEMS):
            for offset, value in zip((0.027, -0.027), dm_lines(rows[(system, project)])):
                label(centers[system_index], y + offset, value)
            for offset, value in zip((0.035, 0.0, -0.035), dc_lines(rows[(system, project)])):
                label(centers[system_index + 3], y + offset, value)
    ax.plot([left, right], [0.182, 0.182], color="black", lw=0.4)
    ax.plot([left, right], [0.072, 0.072], color="black", lw=0.6)
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    pixel_width = fig.get_figwidth() * fig.dpi
    for artist in artists:
        box = artist.get_window_extent(renderer)
        assert box.x0 >= 0 and box.x1 <= pixel_width, f"Text outside five-inch preview: {artist.get_text()}"
    fig.savefig(STEM.with_suffix(".png"), dpi=300)
    fig.savefig(STEM.with_suffix(".pdf"))
    dimensions = tuple(int(v) for v in fig.canvas.get_width_height())
    plt.close(fig)
    return dimensions


if __name__ == "__main__":
    data = read_rows()
    write_tex(data)
    pixels = write_preview(data)
    print(f"PASS: 6 project rows x 6 approach cells; five-inch preview {pixels[0]}x{pixels[1]} px; no text extends past page width")
    print(f"Wrote {STEM.with_suffix('.tex').relative_to(ROOT)}")
    print(f"Wrote {STEM.with_suffix('.png').relative_to(ROOT)}")
    print(f"Wrote {STEM.with_suffix('.pdf').relative_to(ROOT)}")
