#!/usr/bin/env python3
"""Generate the issue report and a PDF with numbered highlights and comments."""
from collections import Counter, defaultdict
from pathlib import Path
import hashlib
import json
import re
import pymupdf

from review_data import ISSUES

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CFP = "https://conf.researchr.org/track/fse-2027/fse-2027-papers"

INTRO = """# FSE 2027 review of ArchLinker

Review date: 2026-09-30. Paper snapshot: `297bf657ee51fe9843c4e5bf32143a01c42c7357`.
The parent checkout was already dirty; its initial status and file hashes are in
[`evidence/snapshot.json`](evidence/snapshot.json). The manuscript was clean.
This review concerns the current rendered full paper, including figures, tables,
references, and both appendices. Historical notes were used only as leads and
checked against current text, code, or recorded results.

**Assessment: reject in its present form.** This is a simulated review judgment,
not an official FSE decision or a prediction about individual reviewers. The
recorded headline score gains reproduce, but several central explanations do
not match the experiment or implementation. A revised paper could retain a
useful empirical contribution after correcting these issues. Whether a major
revision is sufficient depends on the results of those corrections and the
evidence for a contribution beyond existing workflows.

The official FSE 2027 criteria are **originality, importance of contribution,
soundness, evaluation, quality of presentation, and appropriate comparison to
related work**. The assessments below use these criteria rather than inventing
an official numerical score. Open-science and format checks are additional
submission requirements. [Official call](https://conf.researchr.org/track/fse-2027/fse-2027-papers).

| FSE criterion | Assessment | Main findings |
|---|---|---|
| Originality | The specific combination may be useful, but priority claims and the distinctive evidence mechanism are not established. | 12, 13, 25 |
| Importance | Architecture traceability and missed components are relevant SE problems; deployment utility of the metric suite remains a hypothesis. | 15, 18, 29, 30 |
| Soundness | Several verified discrepancies affect method descriptions, examples, metrics, and causal conclusions. | 3–11, 14–17, 20, 24, 26, 27 |
| Evaluation | Saved-link results reproduce; the judge treatment, cost provenance, adaptive development, and uncertainty limit interpretation. | 3, 4, 9–11, 19, 21, 22, 25, 36 |
| Presentation | The main argument is understandable, but worked figures and an ablation table are misleading, with additional wording/layout defects. | 5, 6, 15, 18, 28, 32, 34, 35 |
| Comparison to related work | Closest work is cited, but its capabilities and the opening prior-result number are inaccurately characterized. | 12, 13, 33 |

## What the paper contributes, and what the evidence supports

The primary question is whether a training-free LLM workflow can recover
architecture-document-to-component links more effectively on the selected
benchmark. A shared alias stage feeds two routes; accepted links are composed
with a fixed component-to-code mapping for the downstream task. A second
contribution is a diagnostic suite that exposes variation among components.

The strongest parts are the matched-backend baseline comparison, the published
per-project results (including losses), the preservation of run-level artifacts,
and the explicit separation of candidate generation from filtering. The metric
motivation correctly points out that aggregate scores can conceal group-level
failures. These strengths survive the problems below; the review does not treat
a reporting error as proof that all experimental results are invalid.

For s126 and Artemis on **GPT-5.6-terra, five projects, three runs each**, the
current saved-link macro averages reproduce these differences:

| Metric | ArchLinker | Artemis | Difference (pp) |
|---|---:|---:|---:|
| Doc-model F1 | 0.9362 | 0.8093 | 12.69 |
| Doc-model F2 | 0.9548 | 0.8282 | 12.66 |
| Doc-code F1 | 0.8785 | 0.8127 | 6.58 |
| Doc-code F2 | 0.8962 | 0.8435 | 5.27 |
| Worst-component doc-code F1 | 0.7644 | 0.4684 | 29.60 |
| Harmonic component doc-code F1 | 0.9105 | 0.6347 | 27.58 |

Source: `evaluation/reports/RQ12_BIGTABLE.csv`; independently regenerated by the
existing engines and checked by this review's `audit.py`. The displayed input
CSV has four-decimal precision. These are descriptive benchmark differences,
not estimates of performance on previously unseen projects.

## Argument map

1. Vocabulary differences and contextual references complicate linking.
   **Supported as a task motivation; the claim that all baselines mostly use
   word overlap is not supported (12).**
2. Shared aliases, separate routes, and evidence-informed filtering address
   these problems. **A plausible design; important actual filters and judge
   inputs differ from the description (7, 8, 24).**
3. Higher recorded benchmark scores and ablations demonstrate a contribution.
   **The full-system numerical comparison reproduces, but the judge treatment
   and mechanism attribution need correction (3, 10, 25, 27).**
4. Unequal component link counts make aggregate scores incomplete diagnostics.
   **Supported, but the Gini illustration and some denominators are wrong
   (14–18).**
5. Larger gaps under new component metrics establish architectural usefulness.
   **This transition remains a hypothesis; the metrics encode preferences that
   are not independently validated (29, 30).**

## Highest-priority repairs, in dependency order

1. Freeze and identify the exact evaluated method, benchmark, baseline releases,
   and invocation sets. Reconcile descriptions, prompts, gates, and worked
   examples with that snapshot (5–9, 19, 23, 24, 36).
2. Correct RQ3's intervention and set accounting; align cost and quality
   invocations; expose composition and metric-domain differences (3, 4, 16, 17,
   27, 28).
3. Rebuild the claim-to-evidence chain: fix Gini/CMR/importance interpretations,
   qualify contamination and compute explanations, and describe backend
   sensitivity (10, 11, 14, 15, 18, 20–22, 29–31).
4. Establish the narrow contribution against the actual closest work. Either
   supply the missing mechanism/independent-evaluation evidence or reduce the
   claims to the exploratory scope the current data supports (9, 12, 13, 25,
   26, 33).
5. Release an anonymous, reproducible package; regenerate corrected figures and
   tables; prepare the compliant submission PDF and finish the prose pass
   (1, 2, 6, 23, 28, 32, 34, 35).

## Numbered findings

“Verified” means the stated textual discrepancy, mathematical counterexample,
implementation behavior, or evidence gap was checked. It does **not** mean that
an unperformed experiment is known to fail. Where an interpretation would need
new evidence, the repair says so. “Blocker” means the current deliverable needs
resolution before submission; it is not a prediction of a formal desk decision.

Each ID appears as a highlight/comment in
[`paper-annotated.pdf`](paper-annotated.pdf). Open PDF comments if a viewer only
shows the numbered marker. The report gives the full finding and repair.
"""

ENDING = """
## Coverage and remaining evidence gaps

| Material reviewed | Findings |
|---|---|
| Abstract and introduction | 9, 12–15, 25, 32–34 |
| Motivation and Figures 1–2 | 5, 17, 18, 22 |
| Method and Figures 3–5 | 6–8, 23–26 |
| Metric definitions and Table 1 | 14–16, 18, 29, 30 |
| Experimental design | 3, 9–11, 19–22, 25, 36 |
| Results and Tables 2–6 | 3–5, 15–18, 21, 22, 27, 28 |
| Discussion and conclusion | 9–11, 13, 17, 20, 29–31 |
| Related work and reference attribution | 12, 13, 33, 34, 36 |
| Availability, appendices, prompt templates, layout | 1, 2, 6, 8, 19, 23, 26, 28, 35 |

The evidence still needed for stronger claims is specific: a frozen evaluation
outside development data; an equal-compute alternative if excluding extra
computation as an explanation; fixed-candidate evidence-input comparisons for
the distinctive judging claim; adjudicated semantic labels for claims about
hallucinations; and a stated utility criterion or study if claiming that the new
metrics track practitioner needs better. These are not all mandatory additions
to a narrower descriptive paper. They are necessary only for the respective
stronger conclusions.

Safe wording examples, preserving the current evidence:

- “On the five benchmark projects, the recorded terra runs have higher mean
  doc-model F1 than the matched-backend Artemis runs.”
- “CMR is zero when each gold-documented component has at least one correctly
  recovered sentence link.”
- “The ablations quantify changes under the specified removals; they do not
  distinguish the workflow design from an equal-budget alternative.”
- “Possible pretraining exposure and adaptive development on this benchmark
  remain threats to transfer.”
- “These component-level summaries complement link-level scores; their utility
  for selecting tools in practice has not been established here.”

## Verification and limitations of this review

- A fresh isolated Tectonic 0.15.0 build exits 0 and produces 31 pages. It reports
  layout/font warnings and a bibliography rerun-limit warning. No `??` markers
  were found in the rendered PDF; this was not a warning-free build.
- `gen_csv_to_temp.py` regenerates the RQ1/RQ2, RQ3/RQ4, downstream, and usage
  outputs and finds them identical to the **current working copies**. Some
  working copies were already uncommitted before the review; the tool's generic
  “committed repo copies” wording must not be read as an independent Git-state
  verification.
- `scripts/verify.sh` passes the frozen metric panel and numeric-checker self
  test, then **exits 1**: its numeric-claim ledger reports **71 errors over 219
  active statements**, largely stale/unreviewed wording. These are ledger
  failures, not 71 demonstrated mathematical errors, and are separate from the
  numbered review findings. The failed gate has not been suppressed or reset.
- `audit.py` independently replays the relevant saved candidates and predictions,
  calculates corrected filter-only comparisons, audits cost model labels,
  checks metric exclusions, checks example decisions and antecedents, and
  supplies mathematical counterexamples. It makes no new LLM calls.
- The closest Artemis and LiSSA primary papers and the official FSE 2027 call
  were read directly. The repository's existing bibliography audit was consulted
  as a lead; this review does not claim to have independently checked the
  claim-level entailment of all 72 literature entries. Unverified priority and
  causal claims were treated as unsupported, not disproven.
- No new live baseline or LLM experiment and no independent gold-label
  adjudication was performed. Saved-state reconstructions measure those fixed
  invocations; they do not establish what a newly executed pipeline would do.

Commands, configuration, text output, and input hashes are preserved in
[`VERIFICATION.md`](VERIFICATION.md) and [`evidence/`](evidence/). The paper's
scientific text and other pre-existing working changes were not edited by this
review.
"""


def render():
    assert len(ISSUES) == 36
    assert len({i["id"] for i in ISSUES}) == len(ISSUES)
    counts = Counter(i["severity"] for i in ISSUES)
    intro = INTRO + "\n**Inventory:** " + ", ".join(f"{counts[s]} {s.lower()}" for s in
        ["Blocker", "High", "Medium", "Low"]) + "; 36 findings total.\n\n"
    intro += "| ID | Severity | Problem | Page |\n|---|---|---|---:|\n"
    for i in ISSUES:
        intro += f"| [{i['id']}](#{i['id'].lower()}) | {i['severity']} | {i['title']} | {i['page']} |\n"
    sections = []
    for i in ISSUES:
        source = f"[{i['source']}:{i['line']}]({ROOT / i['source']}:{i['line']})"
        sections.append(f"""<a id="{i['id'].lower()}"></a>

### {i['id']} — {i['title']}

**Severity:** {i['severity']} · **Status:** {i['status']} · **FSE:** {i['criteria']}

**Location:** PDF p.{i['page']}; {source}. Anchor: “{i['anchor']}”.

**Problem and consequence:** {i['problem']}

**Evidence examined:** {i['evidence']}

**Minimal repair:** {i['repair']}

**Recheck:** {i['recheck']}
""")
    (HERE / "REVIEW.md").write_text(intro + "\n".join(sections) + ENDING)
    (HERE / "issues.json").write_text(json.dumps(ISSUES, indent=2) + "\n")

    base = HERE / "evidence/main.pdf"
    doc = pymupdf.open(base)
    palette = {"Blocker": (0.85, 0.12, 0.15), "High": (1, 0.40, 0.05),
               "Medium": (0.80, 0.65, 0.02), "Low": (0.15, 0.45, 0.85)}
    used = defaultdict(list)
    records = []
    for issue in ISSUES:
        page = doc[issue["page"] - 1]
        anchor = issue["anchor"]
        matches = page.search_for(anchor)
        # A small number of anchors need their PDF-specific punctuation/spelling.
        if not matches:
            alternatives = {
                "FSE-02": "DETAILED RESULTS", "FSE-16": "at least one trace link",
                "FSE-08": "earlier-sentence constraint", "FSE-35": "module ablation, run 1",
            }
            anchor = alternatives.get(issue["id"], anchor)
            matches = page.search_for(anchor)
        if not matches:
            raise ValueError(f"Unresolved PDF anchor: {issue['id']} p.{issue['page']} {anchor!r}")
        color = palette[issue["severity"]]
        # Highlight the first text occurrence, possibly split over several lines.
        rects = [matches[0]]
        for rect in matches[1:]:
            if rect.y0 - rects[-1].y0 < 18:
                rects.append(rect)
            else:
                break
        highlight = page.add_highlight_annot(rects)
        highlight.set_colors(stroke=color)
        highlight.set_opacity(.24)
        content = (f"{issue['id']} [{issue['severity']}] {issue['title']}\n\n"
                   f"{issue['problem']}\n\nRepair: {issue['repair']}\n\n"
                   f"Recheck: {issue['recheck']}\n\nSee REVIEW.md for evidence and source location.")
        highlight.set_info(title="FSE review", subject=issue["id"], content=content)
        highlight.update()
        y = max(30, min(rects[0].y0, page.rect.height - 35))
        while any(abs(y - prev) < 12 for prev in used[issue["page"]]):
            y += 12
        used[issue["page"]].append(y)
        marker = page.add_freetext_annot(
            pymupdf.Rect(page.rect.width-40, y, page.rect.width-1, y+11),
            issue["id"], fontsize=5.8, text_color=color, fill_color=(1,1,1), align=1)
        marker.set_info(title="FSE review", subject=issue["id"])
        marker.update()
        records.append({"id": issue["id"], "page": issue["page"],
                        "anchor": anchor, "rectangles": [list(r) for r in rects]})
    target = HERE / "paper-annotated.pdf"
    doc.save(target, garbage=4, deflate=True)
    doc.close()
    checked = pymupdf.open(target)
    ids = Counter(a.info.get("subject") for page in checked for a in (page.annots() or []))
    assert all(ids[i["id"]] == 2 for i in ISSUES), ids
    assert len(checked) == 31
    original = pymupdf.open(base)
    # FreeText annotations contribute to text extraction. Remove review annotations
    # in memory only before comparing the underlying manuscript text.
    for page in checked:
        for annotation in list(page.annots() or []):
            if annotation.info.get("subject", "").startswith("FSE-"):
                page.delete_annot(annotation)
    assert all(original[n].get_text() == checked[n].get_text() for n in range(len(original)))
    for i in ISSUES:
        source = ROOT / i["source"]
        assert source.is_file() and 0 < i["line"] <= len(source.read_text().splitlines())
    (HERE / "evidence/annotation-check.json").write_text(json.dumps({
        "findings": len(ISSUES), "severity_counts": dict(counts), "pages": len(checked),
        "annotations": sum(ids.values()), "all_anchors_resolved": True,
        "page_text_unchanged": True, "base_pdf_sha256": hashlib.sha256(base.read_bytes()).hexdigest(),
        "marked_pdf_sha256": hashlib.sha256(target.read_bytes()).hexdigest(), "anchors": records}, indent=2)+"\n")
    print("PASS: 36 findings, 36 resolved PDF anchors, 72 annotations, 31 pages; original page text unchanged.")
    print("Severity counts:", dict(counts))


if __name__ == "__main__":
    render()
