#!/usr/bin/env python3
"""MANUAL adjudication of the CH2 'type 1' false positives, one by one.

Type 1 = a false positive on a sentence that DOES carry a surface form of the
wrongly linked component (auto_surface != none) but is about something else.  This
is the failure mode `paper/sections/approach.tex` L20-22 and `motivation.tex`
actually assert as Challenge 2: "the approach can return a link that reads as
plausible but has no support in the sentence", illustrated lexically.

Population: the 107 rows of `ch2_fp_sheet.csv` that are NOT in `ch2_mode2_sheet.csv`
(join on project+sentence+wrong_component).  `ch2_mode1_report.py` derives it and
asserts exact coverage against this file; nothing here is hand-counted.

The companion `CH2-mode2-analysis.md` covers the complement (type 2).

Sub-modes (one per item, the dominant one):
  r  OTHER COMPONENT'S RESPONSIBILITY -- a genuine name form of the component is
     present, but the sentence asserts what a DIFFERENT component does; the named
     one is only the object/counterparty.  The paper's exact case.
  q  QUALIFIER / COMPOUND -- the matched string is a modifier inside a longer
     nominal that denotes something else ("database access", "web socket",
     "client-side", "UI name", "FreeSWITCH Event Socket Layer", "back end").
  o  ORDINARY ENGLISH -- the matched string is a common word used in its ordinary
     sense, denoting no component at all ("a little bit of logic", "the most common
     format", "test failures", "a 32 CPU core server").
  t  THIRD-PARTY TECHNOLOGY -- the matched string names the platform/protocol the
     component is named after (GAE, WebRTC, redis, SFU) and the sentence is about
     that technology, not the component.
  s  SHARED-TOKEN SIBLING -- the matched token is shared with a sibling/variant
     component that is the real subject (HTML5 Client vs bbb-html5 = HTML5 Server,
     Redis DB vs redis pubsub).
  p  PACKAGE-PATH INVENTORY -- the match is on a dotted code identifier
     (logic.api, storage.entity, common.util, e2e.util, client.util, test.driver)
     in a package-listing sentence, not on a prose mention of the component.
  l  LIST / CROSS-REFERENCE -- the name occurs in an enumeration or names a
     different component as the target of the claim ("x.logic contains test cases
     for testing the Logic component").
  g  NO TRAP, GOLD GAP -- the matched string genuinely denotes the component and
     the sentence genuinely describes it; the gold standard simply has no link
     here.  These are not lexical traps at all.

gold_silent: does the sentence actually describe that component's responsibility,
so that the gold standard, not the system, is arguably what is wrong?
  yes | borderline | no

surface_bogus: non-empty when `auto_surface` OVERSTATES the lexical evidence, i.e.
the matched string is not a reference-capable name form of this component here
(ordinary English word, generic head noun counted as distinctive, an over-broad
alias, or a token borrowed from an unrelated compound).  The string is the reason.

Each verdict was reached by reading the sentence and its neighbours in the SAD.
"""

# (project, sentence, wrong_component):
#     (sub-mode, gold_silent, surface_bogus, evidence quote, note)
ANNOTATIONS = {

# ---- bigbluebutton -------------------------------------------------------
 ("bigbluebutton",5,"BBB web"): ("q","no","'web' of 'web application' counted as a distinctive token of BBB web",
   "a single page, responsive web application",
   "the web application described IS the HTML5 client; 'BigBlueButton web application' is the alias of BBB web, so the generic phrase collides with it"),
 ("bigbluebutton",5,"WebRTC-SFU"): ("t","no","",
   "WebRTC for sending/receiving audio and video",
   "WebRTC is the browser API the client is built on, not the WebRTC-SFU component"),
 ("bigbluebutton",6,"BBB web"): ("q","no","'web' of 'web socket'",
   "making a web socket connection",
   "'web socket' is a transport, not bbb-web"),
 ("bigbluebutton",16,"HTML5 Client"): ("q","no","partial_g: the generic head noun 'client' inside 'client-side'",
   "a single nodejs process for all client-side communication",
   "the subject is the HTML5 server's nodejs process; 'client-side' is an adjective"),
 ("bigbluebutton",18,"HTML5 Server"): ("o","no","partial_g: 'server' here is a physical machine",
   "having a 16 or 32 CPU core server for BigBlueButton 2.2",
   "hardware, not the HTML5 server component"),
 ("bigbluebutton",19,"BBB web"): ("q","no","'bbb' taken from the unrelated identifier 'bbb-html5'",
   "moves away from a single nodejs process for bbb-html5",
   "bbb-html5 is the HTML5 server; only the shared 'bbb' prefix matched"),
 ("bigbluebutton",20,"BBB web"): ("q","no","'bbb' taken from 'bbb-html5'",
   "this means that bbb-html5 could use multiple CPU cores",
   "same prefix collision"),
 ("bigbluebutton",20,"HTML5 Client"): ("s","no","",
   "bbb-html5 could use multiple CPU cores for processing messages",
   "'html5' is shared with the sibling HTML5 Server, whose alias bbb-html5 is the subject"),
 ("bigbluebutton",21,"BBB web"): ("q","no","'bbb' taken from 'bbb-html5'",
   "bbb-html5 uses 2 'frontend' and two 'backend' processes",
   "same prefix collision"),
 ("bigbluebutton",21,"HTML5 Client"): ("s","no","",
   "bbb-html5 uses 2 'frontend' and two 'backend' processes",
   "sibling HTML5 Server (bbb-html5) is the subject"),
 ("bigbluebutton",27,"Redis DB"): ("s","no","",
   "Frontends handle completely the Streamer redis events",
   "the redis traffic here is pubsub, not the Redis DB sibling"),
 ("bigbluebutton",27,"Redis PubSub"): ("q","borderline","",
   "handle completely the Streamer redis events",
   "'redis events' does denote pubsub traffic but the claim is about the frontends"),
 ("bigbluebutton",31,"Redis DB"): ("s","no","",
   "individual backends only process redis events",
   "pubsub traffic, not the Redis DB sibling"),
 ("bigbluebutton",31,"Redis PubSub"): ("q","borderline","",
   "only process redis events for the meetings matching the associated instanceId",
   "the claim is about backend process sharding"),
 ("bigbluebutton",33,"BBB web"): ("q","no","'bbb' taken from the CLI name 'bbb-conf'",
   "sudo bbb-conf --setip <hostname>",
   "bbb-conf is a shell tool, not the web application"),
 ("bigbluebutton",50,"Recording Service"): ("g","yes","",
   "the Recording Processor will take all the recorded events ... for processing",
   "'Recording Processor' is the run's own alias for Recording Service and the sentence IS its responsibility; the component carries no gold link anywhere in the project"),
 ("bigbluebutton",60,"FreeSWITCH"): ("q","no","canonical fired on the prefix of a LONGER alias bound to a different component ('FreeSWITCH Event Socket Layer' -> FSESL)",
   "Communication between apps and FreeSWITCH Event Socket Layer (fsels)",
   "THE textbook Challenge-2 item: the name FreeSWITCH is present but the phrase names FSESL; gold here is Apps+FSESL+Redis PubSub"),
 ("bigbluebutton",68,"HTML5 Server"): ("o","no","partial_g: 'server' of 'media server'",
   "Kurento Media Server KMS is a media server",
   "a different server entirely; gold is kurento"),
 ("bigbluebutton",68,"WebRTC-SFU"): ("t","no","",
   "implements both SFU and MCU models",
   "SFU is the generic media-routing model here, paired with MCU; gold is kurento"),
 ("bigbluebutton",74,"WebRTC-SFU"): ("t","borderline","",
   "WebRTC provides the user with high-quality audio with lower delay",
   "a claim about the WebRTC protocol's quality, not the SFU component"),
 ("bigbluebutton",75,"Presentation Conversion"): ("o","no","'presentation' of 'a presentation' treated as distinctive",
   "Uploading a presentation.",
   "a section heading about the artefact, not the converter"),
 ("bigbluebutton",76,"Presentation Conversion"): ("g","yes","",
   "Uploaded presentations go through a conversion process",
   "this IS the presentation conversion; gold links only s80-s81 to the component and puts HTML5 Client here"),
 ("bigbluebutton",77,"Presentation Conversion"): ("g","borderline","'presentation' of 'the uploaded presentation'",
   "it needs to be converted into PDF using LibreOffice",
   "a conversion pipeline step; gold is silent"),
 ("bigbluebutton",79,"Presentation Conversion"): ("g","yes","",
   "The conversion process sends progress messages to the client",
   "'the conversion process' anaphorically IS the component; gold assigns only HTML5 Client + Redis PubSub"),
 ("bigbluebutton",82,"Presentation Conversion"): ("g","borderline","'conversion' of 'SWF, SVG and PNG conversion'",
   "enabling and disabling SWF, SVG and PNG conversion",
   "inside the presentation-conversion-flow section; gold is silent"),
 ("bigbluebutton",83,"Presentation Conversion"): ("l","borderline","'conversion' of 'the SVG conversion flow'",
   "Then below the SVG conversion flow.",
   "a pointer to a diagram, no claim about any component"),
 ("bigbluebutton",84,"Presentation Conversion"): ("g","borderline","'conversion' of 'the conversion fallback'",
   "It covers the conversion fallback.",
   "describes the converter's fallback behaviour; gold is silent"),

# ---- jabref --------------------------------------------------------------
 ("jabref",5,"logic"): ("o","no","canonical 'logic' is ordinary English here",
   "has only a little bit of logic attached",
   "the claim is about the model layer; 'logic' is a mass noun, not the logic layer"),
 ("jabref",7,"preferences"): ("o","borderline","canonical 'preferences' is ordinary English here",
   "Only the gui knows the user and his preferences",
   "'his preferences' is the user's settings; the claim is about the gui, though the preferences package does hold them"),

# ---- mediastore ----------------------------------------------------------
 ("mediastore",12,"DB"): ("r","borderline","",
   "The UserDBAdapter component queries the database.",
   "the claim is UserDBAdapter's responsibility; 'the database' is its object, lower-case and unspecific"),
 ("mediastore",27,"DB"): ("q","no","",
   "The MediaAccess component encapsulates database access for meta-data",
   "'database access' -- literally the paper's own qualifier example; the responsibility is MediaAccess's"),
 ("mediastore",29,"DB"): ("q","no","",
   "in order to encapsulate database access for the user data",
   "'database access' again; the responsibility is UserDBAdapter's"),

# ---- teammates -----------------------------------------------------------
 ("teammates",2,"GAE Datastore"): ("t","no","alias 'GAE' is bound to GAE Datastore but GAE is the whole platform",
   "runs on Google App Engine (GAE)",
   "the hosting platform, not the datastore"),
 ("teammates",4,"Client"): ("q","no","canonical 'Client' fired on 'client-side'",
   "JavaScript for client-side interactions such as sorting",
   "the claim is about the UI; 'client-side' is an adjective"),
 ("teammates",12,"Test Driver"): ("o","borderline","'test' counted as a distinctive token of Test Driver",
   "Test data is transmitted using JSON format.",
   "'test data' is a format claim inside the Test Driver section"),
 ("teammates",17,"E2E"): ("g","yes","",
   "Selenium Java is used to automate E2E testing with actual Web browsers",
   "gold links s15/s16 ('its primary function is for E2E tests') but not this one; same subject"),
 ("teammates",18,"Logic"): ("r","no","alias 'back end' -> Logic is over-broad (the back end is Logic+Storage+GAE)",
   "The Client component can connect to the back end directly",
   "the claim is the Client component's capability"),
 ("teammates",22,"Logic"): ("p","borderline","canonical 'Logic' fired on the package segment of 'logic, ui.website, ui.controller'",
   "logic, ui.website, ui.controller represent an application of Model-View-Controller pattern",
   "a package-level design claim, not a Logic responsibility"),
 ("teammates",22,"UI"): ("p","borderline","canonical 'UI' fired on 'ui.website'/'ui.controller'",
   "logic, ui.website, ui.controller represent an application of Model-View-Controller pattern",
   "same sentence, same reason"),
 ("teammates",23,"UI"): ("p","borderline","canonical 'UI' fired on 'ui.website'",
   "ui.website is not a real package.",
   "a claim about a package name, not about the UI component"),
 ("teammates",24,"UI"): ("g","yes","",
   "It is a conceptual package representing the front-end of the application",
   "'front-end' is the run's alias for UI and it genuinely denotes it; gold starts linking UI at the next sentence"),
 ("teammates",26,"UI"): ("p","borderline","canonical 'UI' fired on 'ui.website'",
   "ui.website is not a Java package.",
   "package-name claim"),
 ("teammates",31,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore, but 'GAE server' is the app server",
   "First, request received by the GAE server.",
   "the request pipeline, nothing to do with the datastore"),
 ("teammates",35,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "the automated (GAE server-invoked) requests",
   "the app server invokes them, not the datastore"),
 ("teammates",49,"Common"): ("o","no","canonical 'Common' fired on the adjective 'common'",
   "The most common format is JsonResult",
   "pure ordinary English; the claim is about ActionResult formats"),
 ("teammates",50,"UI"): ("g","yes","",
   "the browser which will then process it on the front-end",
   "'the front-end' is the UI alias and the processing is genuinely the UI's; gold is silent"),
 ("teammates",58,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "requests sent automatically by the GAE server",
   "app server, not datastore"),
 ("teammates",62,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "requests generated by the GAE server are equipped with this privilege",
   "app server, not datastore"),
 ("teammates",69,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "GAE server sends such automated requests through two different configurations",
   "app server, not datastore"),
 ("teammates",73,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "queued by users ... but executed by GAE",
   "the task-queue service of the platform"),
 ("teammates",74,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "the 1 minute standard request processing limit imposed by GAE",
   "a platform quota"),
 ("teammates",79,"Logic"): ("o","yes","canonical 'Logic' fired on 'cascade logic'",
   "Managing relationships between entities, e.g. cascade logic",
   "the matched words are ordinary, but the bullet IS one of the Logic component's listed responsibilities (s77-s78); gold stops at s78"),
 ("teammates",83,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "Connecting to GAE-provided or third-party APIs",
   "a Logic responsibility bullet naming the platform"),
 ("teammates",84,"Logic"): ("p","borderline","canonical 'Logic' fired on 'logic.api, logic.core'",
   "Package overview contains logic.api, logic.core.",
   "a package inventory of the Logic component; no responsibility claim"),
 ("teammates",85,"Logic"): ("p","yes","canonical 'Logic' fired on 'logic.api'",
   "logic.api provides the API of the component to be accessed by the UI",
   "logic.api IS the Logic component's API; gold assigns only UI here"),
 ("teammates",86,"Logic"): ("p","yes","canonical 'Logic' fired on 'logic.core' and on the noun 'logic'",
   "logic.core contains the core logic of the system",
   "the Logic component's own core package; gold is silent"),
 ("teammates",94,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "It connects to GAE's task queue API.",
   "the task queue, not the datastore"),
 ("teammates",117,"Logic"): ("o","borderline","canonical 'Logic' fired on 'cascade logic'",
   "Refer to the API for the cascade logic.",
   "a cross-reference; cascade logic is indeed handled by Logic (s129) but nothing is asserted here"),
 ("teammates",119,"Logic"): ("o","no","canonical 'Logic' fired on the mass noun 'logic'",
   "It contains minimal logic beyond what is directly relevant to CRUD operations",
   "the subject is the Storage component; gold assigns Storage"),
 ("teammates",125,"Storage"): ("p","yes","canonical 'Storage' fired on 'storage.entity'",
   "Classes in the storage.entity package are not visible outside this component",
   "'this component' IS Storage; gold links s123 and s128 but not this one"),
 ("teammates",127,"Common"): ("p","borderline","canonical 'Common' fired on 'common.datatransfer'",
   "These datatransfer classes are in common.datatransfer package",
   "a forward pointer inside the Storage section"),
 ("teammates",130,"Storage"): ("p","borderline","canonical 'Storage' fired on 'storage.api, storage.entity, storage.search'",
   "Package overview contains storage.api, storage.entity, storage.search.",
   "package inventory of Storage"),
 ("teammates",131,"Storage"): ("p","yes","canonical 'Storage' fired on 'storage.api'",
   "storage.api provides the API of the component to be accessed by the logic component",
   "storage.api IS Storage's API; gold assigns only Logic here"),
 ("teammates",132,"Storage"): ("p","borderline","canonical 'Storage' fired on 'storage.entity'",
   "storage.entity contains classes that represent persistable entities",
   "package inventory"),
 ("teammates",133,"Storage"): ("p","borderline","canonical 'Storage' fired on 'storage.search'",
   "storage.search contains classes for dealing with searching and indexing",
   "package inventory"),
 ("teammates",139,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "eventual consistency involving multiple servers in the GAE production environment",
   "a deployment-environment remark"),
 ("teammates",140,"Test Driver"): ("o","no","'test' counted as distinctive",
   "it is expected to avoid test failures caused by eventual consistency",
   "ordinary use of 'test'; the subject is datastore consistency"),
 ("teammates",144,"GAE Datastore"): ("t","no","alias 'GAE' -> Datastore",
   "due to limitations of GAE environment",
   "a platform limitation, not the datastore component"),
 ("teammates",156,"Common"): ("p","borderline","canonical 'Common' fired on 'common.util, common.exceptions, common.datatransfer'",
   "Package overview contains common.util, common.exceptions, common.datatransfer.",
   "package inventory of Common"),
 ("teammates",157,"Common"): ("p","borderline","canonical 'Common' fired on 'common.util'",
   "common.util contains utility classes.",
   "package inventory"),
 ("teammates",158,"Common"): ("p","borderline","canonical 'Common' fired on 'common.exceptions'",
   "common.exceptions contains custom exceptions.",
   "package inventory"),
 ("teammates",159,"Common"): ("p","borderline","canonical 'Common' fired on 'common.datatransfer'",
   "common.datatransfer contains data transfer objects.",
   "package inventory"),
 ("teammates",160,"Common"): ("p","borderline","canonical 'Common' fired on 'common.datatransfer'",
   "common.datatransfer package contains lightweight data transfer object classes",
   "package inventory"),
 ("teammates",169,"Test Driver"): ("p","borderline","canonical 'Test Driver' fired on the path 'test.driver'",
   "Package overview contains test.driver, test.cases and subpackages.",
   "package inventory of the Test Driver component"),
 ("teammates",170,"Test Driver"): ("p","yes","canonical 'Test Driver' fired on 'test.driver'",
   "test.driver contains infrastructure and helpers needed for running the tests",
   "that package IS the Test Driver component; gold is silent"),
 ("teammates",171,"Test Driver"): ("p","borderline","'test' counted as distinctive",
   "test.cases contains test cases.",
   "package inventory"),
 ("teammates",172,"Logic"): ("p","no","canonical 'Logic' fired on the test package 'x.logic'",
   "Sub-packages contains x.testdriver, x.datatransfer, x.util, x.logic, x.storage",
   "x.logic is a TEST package, not the Logic component"),
 ("teammates",172,"Storage"): ("p","no","canonical 'Storage' fired on the test package 'x.storage'",
   "Sub-packages contains ... x.logic, x.storage, x.search, x.webapi",
   "x.storage is a TEST package, not the Storage component"),
 ("teammates",173,"Test Driver"): ("g","yes","",
   "x.testdriver contains component test cases for testing the test driver infrastructure and helpers",
   "the object under test is literally the Test Driver component; gold links Test Driver only at s1/s10/s163/s168"),
 ("teammates",174,"Test Driver"): ("l","no","'test' counted as distinctive",
   "component test cases for testing the datatransfer objects from the Common component",
   "the claim is about Common; gold assigns Common"),
 ("teammates",175,"Test Driver"): ("l","no","'test' counted as distinctive",
   "testing the utility classes from the Common component",
   "the claim is about Common; gold assigns Common"),
 ("teammates",176,"Test Driver"): ("l","no","'test' counted as distinctive",
   "x.logic contains component test cases for testing the Logic component",
   "the claim is about Logic; gold assigns Logic"),
 ("teammates",177,"Test Driver"): ("l","no","'test' counted as distinctive",
   "x.storage contains component test cases for testing the Storage component",
   "the claim is about Storage; gold assigns Storage"),
 ("teammates",178,"Test Driver"): ("l","no","'test' counted as distinctive",
   "x.search contains component test cases for testing the search functions",
   "the claim is about the search functions"),
 ("teammates",179,"Test Driver"): ("l","no","'test' counted as distinctive",
   "x.webapi contains system test cases for testing the user-invoked actions",
   "the claim is about the web API actions"),
 ("teammates",180,"Test Driver"): ("l","no","'test' counted as distinctive",
   "x.automated contains system test cases for testing the system-automated actions",
   "the claim is about the automated actions"),
 ("teammates",181,"Test Driver"): ("o","borderline","'test' counted as distinctive",
   "Some Component tests are pure unit tests",
   "a taxonomy of test kinds, not a claim about the Test Driver component"),
 ("teammates",182,"UI"): ("q","borderline","alias 'front-end' matched inside 'Front-end files'",
   "Front-end files (particularly TypeScript) are tested separately with Jest",
   "the claim is about the testing setup; 'front-end' modifies 'files'"),
 ("teammates",183,"Test Driver"): ("o","no","'test' counted as distinctive",
   "The test cases are found in x.spec.ts files.",
   "a file-location remark"),
 ("teammates",187,"E2E"): ("p","borderline","canonical 'E2E' fired on 'e2e.util, e2e.pageobjects, e2e.cases'",
   "Package overview contains e2e.util, e2e.pageobjects, e2e.cases, x.util, x.e2e, x.lnp",
   "package inventory of the E2E component"),
 ("teammates",188,"E2E"): ("p","yes","canonical 'E2E' fired on 'e2e.util'",
   "e2e.util contains helpers needed for running E2E tests",
   "that package IS the E2E component; gold is silent"),
 ("teammates",189,"E2E"): ("p","borderline","canonical 'E2E' fired on 'e2e.pageobjects'",
   "e2e.pageobjects contains abstractions of the pages as they appear on a Browser",
   "package inventory"),
 ("teammates",190,"E2E"): ("p","borderline","canonical 'E2E' fired on 'e2e.cases'",
   "e2e.cases contains test cases.",
   "package inventory"),
 ("teammates",190,"Test Driver"): ("o","no","'test' counted as distinctive",
   "e2e.cases contains test cases.",
   "'test cases' is ordinary; the package belongs to E2E"),
 ("teammates",191,"Test Driver"): ("l","no","'test' counted as distinctive",
   "x.util contains component test cases for testing the test helpers",
   "the claim is about the test helpers of E2E"),
 ("teammates",192,"E2E"): ("p","borderline","canonical 'E2E' fired on the test package 'x.e2e'",
   "x.e2e contains system test cases for testing the application as a whole",
   "x.e2e is a test package for the E2E component"),
 ("teammates",192,"Test Driver"): ("o","no","'test' counted as distinctive",
   "x.e2e contains system test cases",
   "ordinary use of 'test'"),
 ("teammates",195,"Client"): ("p","borderline","canonical 'Client' fired on 'client.util, client.remoteapi, client.scripts'",
   "Package overview contains client.util, client.remoteapi, client.scripts.",
   "package inventory of the Client component"),
 ("teammates",196,"Client"): ("p","yes","canonical 'Client' fired on 'client.util'",
   "client.util contains helpers needed for client scripts",
   "that package IS the Client component; gold links Client only at s1/s18/s19/s194"),
 ("teammates",197,"Client"): ("p","borderline","canonical 'Client' fired on 'client.remoteapi'",
   "client.remoteapi classes needed to connect to the back end directly",
   "package inventory"),
 ("teammates",197,"Logic"): ("q","no","alias 'back end' -> Logic is over-broad",
   "classes needed to connect to the back end directly",
   "'the back end' is the whole server side; the claim is about client.remoteapi"),
 ("teammates",198,"Client"): ("p","borderline","canonical 'Client' fired on 'client.scripts'",
   "client.scripts scripts that deal with the back end data",
   "package inventory"),
 ("teammates",198,"Logic"): ("q","no","alias 'back end' -> Logic is over-broad",
   "scripts that deal with the back end data for administrative purposes",
   "'the back end data' is the datastore contents; the claim is about client.scripts"),

# ---- teastore ------------------------------------------------------------
 ("teastore",11,"WebUI"): ("q","no","",
   "It matches the provided product ID or UI name",
   "'UI name' is an image FILENAME category; the claim is the Image Provider's lookup; gold assigns ImageProvider"),
 ("teastore",12,"WebUI"): ("q","no","",
   "If the product ID or UI name is not available to the Image Provider",
   "'UI name' again; gold assigns ImageProvider"),
 ("teastore",13,"WebUI"): ("q","no","",
   "If the product ID or UI name is found but not in the requested size",
   "'UI name' again; the claim is image scaling"),
 ("teastore",15,"WebUI"): ("q","no","",
   "If the product ID or UI name and size is found, the image will be loaded and delivered",
   "'UI name' again; the claim is image delivery"),
}

SUBMODE = {
 "r": "other component's responsibility (the paper's exact case)",
 "q": "qualifier / compound points elsewhere",
 "o": "ordinary English, not the component",
 "t": "third-party technology the component is named after",
 "s": "shared-token sibling is the real subject",
 "p": "package-path / code-identifier inventory",
 "l": "list / cross-reference to a different component",
 "g": "NO TRAP -- genuine mention, gold gap",
}
